version: '3.8'

services:
  # 1. PostgreSQL Veritabanı Servisi
  postgres:
    image: postgres:16-alpine
    container_name: telekom_postgres
    restart: always
    environment:
      POSTGRES_DB: telekom_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Redis Ön Bellek Servisi
  redis:
    image: redis:7-alpine
    container_name: telekom_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: